<?php 
$pagetitle = "LBB Contest Rules | Dreamfields Pasta";
$metadescription = "Dreamfields Little Black Box - Contest Rules";
//$keywords = "";


$stylesheet = "home.css";
//define ('JS_SHEET', 'signup2');
//$bodyClass = "";
?>

<?php include('../_includes/subdir_header.php'); ?>

    <div class="site_body">
      <div id="border-gold">
        
        <?php include('../_includes/main_nav.php'); ?>
        
        
        <!-- BEGIN page content -->
        <div class="main-content">
          
          <div class="ca_1">
            <h1 style="text-align:center;">&ldquo;Dreamfields&rsquo; LBB for a Healthier Me  Contest&rdquo; on Pinterest</h1>
            <h2 style="text-align:center;">CONTEST RULES AND REGULATIONS</h2>
            
            <ol class="main">
              <li>NO PURCHASE, CONTRIBUTION OR PAYMENT OF ANY KIND IS NECESSARY TO ENTER OR WIN. A PURCHASE DOES NOT INCREASE CHANCES OF WINNING.  This Contest is in no way sponsored, endorsed or administered by, or associated with Pinterest. You understand that you are providing your information to Dreamfields and not to Pinterest. The Dreamfields privacy policy can be found at <a href="http://www.dreamfieldsfoods.com/privacy-policy.php">http://www.dreamfieldsfoods.com/privacy-policy.php</a></li>

              <li>ELIGIBILITY: The Contest is open only to contestants who sign up at the online contest page and who are 18 years of age or older and of the age of majority in the jurisdiction where they reside as of the date of entry. The Contest is only open to legal residents of the United States, living in one of the 50 United States or the District of Columbia, and is void where prohibited by law. Employees of Dreamfields pasta, their respective affiliates, subsidiaries, advertising and promotion agencies, suppliers and their immediate family members and/or those living in the same household of each are not eligible to participate in the Contest. The Contest is subject to all applicable federal, state and local laws and regulations.  Void where prohibited.</li>

              <li>AGREEMENT TO OFFICIAL RULES: By participating, entrants agree to be fully and unconditionally bound by these Rules, Sponsor&rsquo;s and Administrator&rsquo;s decisions, which are final and binding in all matters related to the Contest and they represent and warrant that they meet the eligibility requirements set forth herein. All federal, state, local laws and regulations apply.</li>

              <li>CONTEST PERIOD: The Contest period begins on February 4, 2015 12:01 A.M. (EST), and continues through February 28, 2015 at 11:59pm EST.  Ten (10) prizes awarded during the Contest period will be selected as specified in the Selection of Winners section of these rules.</li>

              <li>HOW TO ENTER:  Beginning at 12:01 a.m. Eastern Standard Time (EST) on Wednesday, February 4, 2015 through 11:59 p.m. on Saturday, February 28, 2015, (the &ldquo;Contest Entry Period&rdquo;) contest entries can be submitted by filling out the official Entry form on <a href="http://www.trydreamfields.com/contest">www.TryDreamfields.com/Contest</a>.  Only one (1) Entry is permitted per Pinterest account during the Contest Entry Period.  Any other methods of entry will be voided.  Entries that are mechanically reproduced, generated by a script, macro, or create various accounts to circumvent entry restrictions by automated means and/or otherwise not in compliance with these rules will be disqualified..  Entries not meeting all Requirements set forth in Section 6 below, will be disqualified.<br>
<br>
<u><strong>Entries must be received by 11:59 p.m. (EST) on Saturday, February 28, 2015.</strong></u>  Sponsor is not responsible for computer system or phone line, hardware, software or program malfunctions or other errors, failures, delayed computer transmissions or network connections.<br>
<br>
<u><strong>Please note:</strong> There will be no communications or correspondence with any contestants until after the contest judging.</u> </li>
              
              <li>ENTRY REQUIREMENTS:  In order to participate in the Contest, entrants must:
              	<ul>
                  <li>Create a Pinterest Board  (Entry) and name it &ldquo;Dreamfields LBB for a Healthier Me&rdquo; and include pins that  depict steps that you&rsquo;ll take to become healthier in 2015.</li>
                  <li>Check out our &ldquo;Dreamfields  LBB for Healthier Me&rdquo; board for inspiration</li>
                  <li>Adhere to the Restrictions  set forth in Section 7, below.</li>
                  <li>Follow our Pinterest page (<a href="http://www.pinterest.com/dreamfields" target="_blank">www.pinterest.com/dreamfields</a>) and use one or all of the hashtags #HealthyPasta,  #LittleBlackBox and #DreamfieldsPinterestContest in  the comment sections of the Entry pins.</li>
                  <li>Have access to the  Internet, a valid email address and an active Pinterest account. To become a member  of Pinterest, participants may go to pinterest.com/landing to request  membership. Membership to Pinterest is free. Pinterest membership is not  guaranteed.</li>
                </ul>
           	  </li>
              
              <li>RESTRICTIONS: Entries must not contain material that:
              	<ul>
                      <li>References tobacco, smoking or smoking products, or  otherwise contains or depicts someone smoking or intoxicated;</li>
                      <li>Violates or infringes another&rsquo;s rights, including without  limitation, privacy, publicity or intellectual property rights, or that  constitutes copyright infringement;</li>
                      <li>Contains material that promotes bigotry, racism, hatred or  harm against any group or individual or promotes discrimination based on race,  sex, religion, nationality, disability, sexual orientation or age;</li>
                      <li>Contains any unacceptable clothing or adornments, or displays  any commercial/corporate advertising other than that of Sponsor (including but  not limited to corporate logos, brand names, trademarks, slogans, political,  personal and religious statements);</li>
                      <li>Contains indecent, violent, or unsafe behavior or situations,  profanities or obscenities, including but not limited to nudity, or  pornography, or is otherwise inappropriate, indecent, profane, obscene,  hateful, tortuous, slanderous or libelous;</li>
                      <li>References persons without their permission;</li>
                      <li>Contains any personal identification, such as license plate  numbers, personal names, e-mail addresses or street addresses;</li>
                      <li>Contains materials embodying the names, likenesses, voices  or other indicia identifying any person, including, without limitation,  celebrities and/or other public or private figures, living or dead, without  permission;</li>
                      <li>Contains any statements that promote or oppose a political  party or candidate;</li>
                      <li>Disparages any persons or organizations;</li>
                      <li>Includes threats to any person, place, business, or group;</li>
                      <li>Is unlawful, in violation of or contrary to any applicable  federal, state, or local laws and regulations.</li>
                      <li>Entries must be dignified, modest and in good  taste, must not be obscene or indecent, including but not limited to containing  pornography or profanity, nor contain any offensive or defamatory statements  including but not limited to words or symbols that might be considered  offensive to individuals of any race, ethnicity, religion, sexual orientation  or socioeconomic group, nor include threats to any person, place, business, or  group, nor invade privacy or other rights of any person, firm or entity,  including, without limitation, any third party trademarks or copyrights, nor  portray Sponsor or Sponsor&rsquo;s brands or products in any way that might tend to  subject any of them to public contempt, scandal, disrepute or ridicule. Sponsor  reserves the right to make determinations of suitability in its sole and  absolute discretion, and to disqualify any entries it determines to be  inappropriate for any of the reasons listed above, or for any other reason. </li>
                      <li>Entries  must be original; may not have won previous awards; may not have been  previously published; may not be obscene or indecent; cannot be sexually  explicit or suggestive, profane or pornographic, violent or derogatory of any  ethnic, racial, gender, religious, professional or age group; cannot promote  alcohol, illegal drugs, tobacco, firearms/weapons (or the use of any of the  foregoing), any activities that may appear unsafe or dangerous, or any  political agenda or message; cannot be offensive, endorse any form of hate or  hate group; cannot defame, misrepresent or contain disparaging remarks about  Sponsor or its products or services, or other people, products or companies;  cannot communicate messages or images inconsistent with the positive images  and/or goodwill to which Sponsor wishes to associate; may not invade the  privacy or other rights of any person, firm or entity; may not in any other way  violate any applicable federal, state or local laws or regulations; may not  contain any third party trademarks, names or third party logos or any  copyrighted components; and cannot contain any personal identification, such as  license plate numbers, personal names, email addresses or street addresses  (other than as required in the registration).</li>
</ul>
All entries become the exclusive property of Dreamfields.  By entering the Contest, entrant irrevocably grants to Dreamfields and its agents the unconditional and perpetual right to post, display, edit, adapt and publish any or all of the entries submitted in any media without attribution or compensation to the entrant, his or her successors or assigns, or any other entity unless prohibited by law.  
              </li>
              
              <li>SELECTION OF WINNERS: All eligible entries will be judged by a panel of Sponsor and agency representatives based on the following criteria: Creativity (60%) defined as how creatively you interpret the theme; Quality of Pin Story (40%) story defined by the pins and descriptions used. The entry with the highest score at the conclusion of judging will be the Grand Prize winner. The next highest-scoring entry will be the Runner-Up Prize winner. In the event of a tie during judging, tied entries will be re-evaluated and the winner will be determined on the following criteria: Creativity (100%). All prize awards are subject to verification of eligibility. Winning boards will be posted on the contest Pinterest board as well as on <a href="http://www.dreamfieldsfoods.com/">www.DreamfieldsFoods.com</a>, Facebook , Twitter, and Instagram.</li>
              
              <li>PRIZES: The Prizes for the Contest consists of ten (10) prizes. Five grand prizes will consist of one (1) full case of Dreamfields pasta product ($29.88), a branded food scale ($25), a Fitbit or other comparably-priced fitness tracker ($100) and a $100 gift card each, shipped to the five (5) Winner&rsquo;s home addresses. Five Runner-Up prizes will consist of one (1) full case of Dreamfields pasta product ($29.88) and a branded food scale ($25).  A case of Dreamfields pasta consists of twelve (12) boxes of pasta (each box is a 13.25 oz. package). The Approximate Retail Value (ARV) is $1,549. NO ENTRANT IS GUARANTEED TO WIN ANY PRIZE OF ANY KIND. THE ODDS OF WINNING DEPEND ON THE NUMBER OF ENTRIES RECEIVED.<br>
<br>
No substitution of prize or transfer/assignment of prize to others or request for the cash equivalent by winners is permitted. Winner must claim prize by return e-mail and providing such winner&rsquo;s address in an eligible U.S. State within five (5) days of Winner notification. The prize will be sent to winner within thirty (30) days after such winner makes its claim. 
</li>
              
              <li>NOTIFICATION: Winners of the Contest will be notified by e-mail to the e-mail address provided and must respond with their full name, address, city, state, zip code, and daytime phone number within 48 hours of attempted notification. Winner will be required to sign a release form in order to collect their prize. Failure to collect the prizes as instructed, the return of any prizes/prize notifications as undeliverable, Sponsor&rsquo;s inability to contact a potential winner in a reasonable time period, or non-compliance with these Official Rules may result in forfeiture of prize. Dreamfields pasta shall have no liability for a winner&rsquo;s failure to receive notices due to winners&rsquo; spam, junk e-mail or other security settings or for winners&rsquo; provision of incorrect or otherwise non-functioning contact information. If the winner cannot be reached after reasonable efforts have been exerted, or if he/she is found to be ineligible, or if he/she cannot or does not comply with these Contest Rules, such winner will be disqualified and an alternate winner may be selected.</li>
              
              <li>PUBLICITY: Except where prohibited, participation in this Contest constitutes winner&rsquo;s consent to use of winner&rsquo;s name, likeness, voice, opinions and biographical information for publicity, advertising, trade, or promotional purposes in any media or manner, now known or hereafter devised, worldwide, without further payment, consideration, notice or approval.</li>
              
              <li>TERMS: Dreamfields pasta, its suppliers, agents, affiliates, consultants and service providers are not responsible for any typographical or other error in the printing, the offering or the announcement of any prize or in the administration of the promotion, whether caused by computer, technical or human error. Winner assumes all liability and agrees to hold Dreamfields pasta, its suppliers, advertisers, agents, affiliates, consultants and service providers harmless for any injury or damage caused, or claimed to be caused, by participation in this promotion or use or redemption of any prize.<br>
<br>
Dreamfields pasta reserves the right to cancel or modify the program at any time and for any reason, including but not limited to, destruction of the integrity of the promotion by fraud, misconduct or technical failures, or if a computer virus, bug, or other technical problem corrupts the administration, security, or proper administration of the promotion. Dreamfields pasta reserves the right to disqualify, freeze or prohibit the participation of an individual if fraud or tampering is suspected, or if the individual fails to comply with any requirement of participation or with any provision in these Contest Rules. CAUTION: ANY ATTEMPT TO DELIBERATELY DAMAGE OR UNDERMINE THE OPERATION OF THIS PROMOTION MAY BE A VIOLATION OF CRIMINAL AND CIVIL LAWS. DREAMFIELDS PASTA RESERVES THE RIGHT TO DISQUALIFY AND/OR SEEK DAMAGES FROM ANY INDIVIDUAL MAKING ANY SUCH ATTEMPTS TO THE FULL EXTENT PERMITTED BY LAW.
</li>
              
              <li>RELEASE OF LIABILITY; DISCLAIMER OF WARRANTIES: By entering this Contest, entrants release Dreamfields pasta, its suppliers, advertisers, agents, affiliates, consultants and service providers, from any liability, loss, harm, damage, cost or expenses whatsoever incurred which may occur in connection with any part of this Contest and with the acceptance, ownership, and/or use of the prizes. ALL PRIZES, WILL BE AWARDED &ldquo;AS IS,&rdquo; AND DREAMFIELDS PASTA EXPRESSLY DISCLAIMS ALL WARRANTIES, WHETHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION THE IMPLIED WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.</li>
              
              <li>PRIVACY: Personally identifiable information that is submitted by entrants as part of this Contest will be used to administer the Contest, select prize winners and fulfill prizes, and will be treated in accordance with Dreamfields pasta&rsquo;s privacy policy. <a href="http://www.dreamfieldsfoods.com/privacy-policy.html">http://www.dreamfieldsfoods.com/privacy-policy.html</a></li>
              
              <li>GOVERNING LAW/JURISDICTION: all issues and questions concerning the construction, validity, interpretation and enforceability of these official rules or the rights and obligations of entrants or sponsor in connection with the contest shall be governed by and construed in accordance with the internal laws of the state of Minnesota without giving effect to any choice of law of conflict of law rules or provisions that would cause the application of any other state&rsquo;s laws.</li>
              
              <li>ARBITRATION PROVISION:  
Any controversy or claim arising out of or relating to this Promotion shall be settled by binding arbitration at a location within the greater Minneapolis/St. Paul, Minnesota metropolitan area selected by the arbitrator (provided that such location is reasonably convenient for claimant), or at such other location as may be mutually agreed upon by the parties, in accordance with the procedural rules for commercial disputes set forth in the Comprehensive Arbitration Rules and Procedures of JAMS (&ldquo;JAMS Rules and Procedures&rdquo;) then prevailing, and judgment upon the award rendered by the arbitrator(s) may be entered in any court having jurisdiction thereof. The arbitrator shall be selected pursuant to the JAMS Rules and Procedures. The arbitrator shall apply Minnesota law consistent with the Federal Arbitration Act and applicable statutes of limitations, and shall honor claims of privilege recognized at law. In the event that the claimant is able to demonstrate that the costs of arbitration will be prohibitive as compared to the costs of litigation, Sponsor will pay as much of the claimant&rsquo;s filing and hearing fees in connection with the arbitration as the arbitrator deems necessary to prevent the arbitration from being cost-prohibitive. If any part of this arbitration provision is deemed to be invalid, unenforceable or illegal (other than that claims will not be arbitrated on a class or representative basis), or otherwise conflicts with the rules and procedures established by JAMS, then the balance of this arbitration provision shall remain in effect and shall be construed in accordance with its terms as if the invalid, unenforceable, illegal or conflicting provision were not contained herein. If, however, the portion that is deemed invalid, unenforceable or illegal is that claims will not be arbitrated on a class or representative basis, then the entirety of this arbitration provision shall be null and void, and neither claimant nor Sponsor shall be entitled to arbitrate their dispute. Upon filing a demand for arbitration, all parties to such arbitration shall have the right of discovery, which discovery shall be completed within sixty days after the demand for arbitration is made, unless further extended by mutual agreement of the parties. THE ARBITRATION OF DISPUTES PURSUANT TO THIS PARAGRAPH SHALL BE IN THE ENTRANT&rsquo;S INDIVIDUAL CAPACITY AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING. THE ARBITRATOR MAY NOT CONSOLIDATE OR JOIN THE CLAIMS OF OTHER PERSONS OR PARTIES WHO MAY BE SIMILARLY SITUATED. 
DO NOT ENTER THIS PROMOTION IF YOU DO NOT AGREE TO HAVE ANY CLAIM OR CONTROVERSY ARBITRATED IN ACCORDANCE WITH THESE OFFICIAL RULES. 
</li>
              
              <li>CLASS ACTION: No class action suits. By participating in sponsor&rsquo;s sweepstakes, each entrant and prize winner (and his/her parent/legal guardian, if an eligible minor) agrees that to the extent permitted by applicable law: (1) any and all disputes, claims and causes of action arising out of or connected with the sweepstakes, or any prize awarded, will be resolved individually without resort to any form of class action; (2) any and all claims, judgments and awards will be limited to actual third-party, out-of-pocket costs incurred (if any), but in no event will attorneys' fees be awarded or recoverable; (3) UNDER NO CIRCUMSTANCES WILL ANY ENTRANT OR PRIZE WINNER BE PERMITTED TO OBTAIN ANY AWARD FOR, AND ENTRANT HEREBY KNOWINGLY AND EXPRESSLY WAIVES ALL RIGHTS TO SEEK PUNITIVE, INCIDENTAL, CONSEQUENTIAL OR SPECIAL DAMAGES, LOST PROFITS AND/OR ANY OTHER DAMAGES, OTHER THAN ACTUAL OUT OF POCKET EXPENSES, AND/OR ANY RIGHTS TO HAVE DAMAGES MULTIPLIED OR OTHERWISE INCREASED; AND (4) ENTRANT AND PRIZE WINNER'S REMEDIES ARE LIMITED TO A CLAIM FOR MONEY DAMAGES (IF ANY) AND ENTRANT IRREVOCABLY WAIVES ANY RIGHT TO SEEK INJUNCTIVE OR EQUITABLE RELIEF; (5) this Promotion is governed by the laws of the state of Minnesota without regard to its conflicts of law principles and any and all disputes, claims and causes of action arising out of or connected with this Promotion, and except for the arbitration noted above all disputes shall be litigated exclusively before a court of competent jurisdiction located within the state of New Jersey; if any provision or provisions of these official rules shall be held  to be invalid, illegal, unenforceable or in conflict with the law, the validity, legality and enforceability of the remaining provisions shall not in any way be affected or impaired thereby; and (6) entrants shall be bound by these official rules. </li>
              
              <li>WINNERS LIST/OFFICIAL RULES: To obtain a copy of these Official Rules (print this page) and/or any legally-required winners list, send a self-addressed stamped envelope to: Dreamfields LBB for a Healthier Me Pinterest Contest, 155 North Michigan Ave., Suite 609, Chicago, IL 60601. All such requests must be received by 4/1/2015.</li>
              
              <li><span style="text-transform:uppercase">Indemnification Clause:</span> Entrants (and, if eligible minors, their parents or legal guardians) agree (a) that Sponsor and Promotion Parties are released, will have no liability whatsoever for, and shall be held harmless by entrants against any liability for any injuries, losses or damages of any kind to person(s), including death, or property resulting in whole or in part, directly or indirectly, from acceptance, possession, misuse or use of any prize or participation in this Sweepstakes or any Sweepstakes-related activities, including any travel related thereto and (b) except where legally prohibited, winners (and, if eligible minors, their parents or legal guardians) grant (and agree to confirm that grant in writing) permission to Sponsor and those acting under their respective authority the right to the use of his/her name, picture, likeness, persona, voice, image, biographical information and statements, at any time or times, for advertising, trade, publicity and promotional purposes without additional compensation, in all media now known or hereafter discovered, worldwide in perpetuity, and on the Internet and World Wide Web, without notice, review or approval, unless prohibited by law. </li>
            </ol>
            
This Contest is in no way sponsored, endorsed or administered by, or associated with Pinterest.
<br>
<br>
&ldquo;Like&rdquo; Dreamfields today and receive the latest product news and recipes!       
            
            
          </div><!-- .ca_1 -->
          
        </div>
        <!-- END page content -->
        
        
        <?php include('../_includes/footer_nav.php'); ?>
        
      </div><!-- #border_gold -->
    </div><!-- #site_body -->

<?php include('../_includes/subdir_footer.php'); ?>
<script language='javascript'>
  // mark the active page in main nav
  $("#mainnav_privacy").addClass("active");
</script>	

</body>
</html>