<?php 
$pagetitle = "Thanks For Making Dreamfields Part Of Your Healthy Meal Plan | Try Dreamfields Pasta";
$metadescription = "Get a grocery coupon to buy Dreamfields healthy carb living pasta. Same great taste of traditional pasta";
//$keywords = "";


$stylesheet = "general.css";
//define ('JS_SHEET', 'signup2');
$bodyClass = "signup2";

// Get GET vars
$email = ( !empty($_GET['email']) ) ? htmlentities($_GET['email']) : "";
$src = ( !empty($_GET['src']) ) ? $_GET['src'] : "";
?>
<?php
ini_set('display_errors', 0);
//error_reporting(E_ALL);

session_start();

// function that checks if a variable exists
function is($var) {
  if (!isset($var)) return false;
  if ($var!==false) return true;
  return false;
} 

// Coupons.com cipher keys for Dreamfields Pasta
define('SHORT_KEY','qbzua3wyvo'); // Short CipherKey defined by Coupons.com
define('LONG_KEY','O1ZyaJqUEHm69XWsMG74CopVtxz8BQiRe5uKScNjILh3fwdTbPFgDvlA2nrkY'); // Long CipherKey defined by Coupons.com

// Coupons.com URL Algorithm
require_once('_includes/webBricksAlgorithm_PHP4.php');
$o = 114274;  				// (formerly "106048") $1.00 offer code
$c = 'BG';   				// (formerly "DP") Dreamfields Pasta
if (is($_SESSION['email'])) { 
  $p = $_SESSION['email']; 	// pin code (<=50 character unique to coupon user - email address)
  //echo "p1 is " . $p;
} else {
  //$_SESSION['email'] = 'blah';	
  //$p = $_SESSION['email'];
}


$pGet = (isset($_GET['p'])) ? $_GET['p'] : false; 		// pin code (<=50 character unique to coupon user - email address) - possibly retrieved from query string
$cc = (isset($_GET['cc'])) ? $_GET['cc']: false; 		// md5 hash of pin code, generated by ExactTarget (possibly in query string, if user came from an ET email)
$cpt = ''; 					// encrypted string (generated by this script)

// If the session variable of $p does not exist, then
// use the $p value from the query string (i.e., from ET email)
if(!is($p)) {
	$p = $pGet;
	//echo("p is now " . $p);
}

/* If the user came from an ET email, there will be a $cc value.
   $cc is an md5 hash of the pin code (email address of the ET subscriber).
   So, if $cc exists, we check to make sure the md5 hash is legit
   If it is not legit, we redirect the user to an error page. */
if(is($cc)) {
	//echo("cc is " . $cc);
	// check md5 hash - if bad go to coupons.com error
	//echo("<br><br>".md5($p));
	//echo("<br><br>cc is " . $cc);
	if (md5($p) != $cc) {
		//echo("<br><br>why no redirect?");
		//header('Location: http://bricks.coupons.com/enable.asp?eb=1&o='.$o.'&c='.$c.'&p='.$p.'&cpt=');
		header('Location: http://www.dreamfieldsfoods.com/');
	}
}


// Generate a Coupon URL to be used on this web page
$cpt = getCpt($o,$c,$p);
$couponURL = 'http://bricks.coupons.com/enable.asp?eb=1&o='.$o.'&c='.$c.'&p='.urlencode($p).'&cpt='.$cpt;

session_destroy();
?>


<?php include('_includes/header.php'); ?>

    <div class="site_body">
      <div id="border-gold">
        
        <?php include('_includes/main_nav.php'); ?>
        


        
        <!-- BEGIN page content -->
        <div class="main-content">
          
          <div class="ca_1">
            
            
            <h1>Check Your Email Inbox</h1>
            <p>Thanks for your interest in Dreamfields Pasta. Check your email inbox to print your coupon. For more information about our pasta, please visit <a href="http://www.dreamfieldsfoods.com/" target="_parent">DreamfieldsFoods.com</a>.</p>
            
              
          </div><!-- .ca_1 -->
          
          
          
          
        </div>
        <!-- END page content -->
        
        
        <?php include('_includes/footer_nav.php'); ?>
        
      </div><!-- #border_gold -->
    </div><!-- #site_body -->

<?php include('_includes/footer.php'); ?>
<script language='javascript'>
  // mark the active page in main nav
  //$("#mainnav_home").addClass("active");
</script>	

<?php include('_includes/inc_GoogRetargetThanks_v01.php'); ?>
</body>
</html>