<?php 
$pagetitle = "Pastapalooza Contest Rules | Dreamfields Pasta";
$metadescription = "Dreamfields Pastapalooza - Contest Rules";
//$keywords = "";


$stylesheet = "general.css";
//define ('JS_SHEET', 'signup2');
//$bodyClass = "";
?>

<?php include('../_includes/subdir_header.php'); ?>

    <div class="site_body">
      <div id="border-gold">
        
        <?php include('../_includes/main_nav.php'); ?>
        
        
        <!-- BEGIN page content -->
        <div class="main-content">
          
          <div class="ca_1">
            <h1 style="text-align:center;">Dreamfields&rsquo; PASTAPALOOZA V Contest</h1>
            <h2 style="text-align:center;">CONTEST RULES AND REGULATIONS</h2>
            
            
<ol class="main">            
    
            
<li>
NO PURCHASE, CONTRIBUTION OR PAYMENT OF ANY KIND IS NECESSARY  TO ENTER OR WIN. A PURCHASE DOES NOT  INCREASE CHANCES OF WINNING.  The  Dreamfields privacy policy can be found at <a href="http://www.dreamfieldsfoods.com/privacy-policy.php" target="_blank">http://www.dreamfieldsfoods.com/privacy-policy.php</a>
</li>


<li>ELIGIBILITY: The  Contest is open only to contestants who sign up at the online contest page and  who are 18 years of age or older and of the age of majority in the jurisdiction  where they reside as of the date of entry. The Contest is only open to legal  residents of the United States, living in one of the 50 United States or the  District of Columbia, and is void where prohibited by law. Employees of  Dreamfields pasta, their respective affiliates, subsidiaries, advertising and  promotion agencies, suppliers and their immediate family members and/or those  living in the same household of each are not eligible to participate in the  Contest. The Contest is subject to all applicable federal, state and local laws  and regulations. Void where prohibited.</li>


<li>AGREEMENT TO OFFICIAL RULES: By participating,  entrants agree to be fully and unconditionally bound by these Rules, Sponsor&rsquo;s  and Administrator&rsquo;s decisions, which are final and binding in all matters  related to the Contest and they represent and warrant that they meet the  eligibility requirements set forth herein. All federal, state, local laws and  regulations apply.</li>


<li>CONTEST PERIOD: The Contest period begins on May 21, 2015 at 12:01  a.m. (EDT) and continues through August 19, 2015 at 11:59pm (EDT).  Thirty (30) prizes will be awarded during the  Contest period and will be selected as specified in the Selection of Winners  section of these rules.</li>


<li>HOW TO ENTER: There will be five voting periods in which to  participate:
<ul>
  <li>12:01 a.m. Eastern Daylight Time (EDT)  on Thursday, May 21, 2015 through 11:59 p.m. on Wednesday, May 27, 2015;</li>
  <li>12:01 a.m. Eastern Standard Time (EDT)  on Thursday, June 11, 2015 through 11:59 p.m. on Wednesday, June 17, 2015;</li>
  <li>12:01 a.m. Eastern Standard Time (EDT)  on Thursday, July 2, 2015 through 11:59 p.m. on Wednesday, July 8, 2015;</li>
  <li>12:01 a.m. Eastern Standard Time (EDT)  on Thursday, July 23, 2015 through 11:59 p.m. on Wednesday, July 29, 2015; and</li>
  <li>12:01 a.m. Eastern Standard Time (EDT)  on Thursday, August 13, 2015 through 11:59 p.m. on Wednesday, August 19, 2015.</li>
</ul>
Votes for recipes created by bloggers in the  Market Basket Challenges can be submitted by clicking on the &ldquo;vote&rdquo; button next  to the recipe image on the official contest voting page at <a href="http://www.TryDreamfields.com/Pastapalooza">www.TryDreamfields.com/Pastapalooza</a>.<strong>  </strong>Only one (1) Vote is permitted per day  per email account.  Any other methods of  entry will be voided.  Entries that are  mechanically reproduced, generated by a script, macro, or create various  accounts to circumvent entry restrictions by automated means and/or otherwise  not in compliance with these rules will be disqualified.  Entries not meeting all Requirements set  forth in Section 6 below, will be disqualified.<br>
<br>
Sponsor is not responsible for computer system  or phone line, hardware, software or program malfunctions or other errors,  failures, delayed computer transmissions or network connections.<br>
<br>
<strong><u>Please  note:</u></strong><u> There will be no communications or correspondence with any contestants until after the voting for each Market Basket Challenge is over.</u></li>


<li>VOTING  REQUIREMENTS:  In order to participate in  the Contest, entrants must:
<ul style="margin-bottom: 0px;">
  <li>Go to the contest voting  page, <a href="http://www.TryDreamfields.com/Pastapalooza">www.TryDreamfields.com/Pastapalooza</a>  to review the blogger  recipe entries.</li>
  <li>Submit name and email  address.</li>
  <li>Click on the &ldquo;vote&rdquo; button  next to the recipe entry of choice.</li>
  <li>Adhere to the Restrictions  set forth in Section 7, below.</li>
</ul>
</li> 


<li>RESTRICTIONS: Only one vote per  email address per day is allowed.</li>


<li>SELECTION OF WINNERS: The  recipe with most votes at the end of the voting period in each of the Market  Basket Challenges will win the Blogger Grand Prize; the other four recipes will  be considered Runners-Up.  Additionally,  one randomly-selected participant from all who voted in each Market Basket  Challenge will also win an Entrant Grand Prize.   Winners names will be posted on <a href="http://www.DreamfieldsFoods.com">www.DreamfieldsFoods.com</a>, Facebook , Twitter, and Instagram.</li>


<li>PRIZES: The Prizes  for the Contest consists of thirty (30) prizes. Five (5) Blogger Grand Prizes  will consist of a $1,000 donation made in the name of the winner to the food  bank/pantry of choice. Twenty (20) Runner-Up Prizes will consist of a $200  donation made in the name of the winner to the food bank/pantry of choice.  Five (5) Entrant Grand Prizes will consist of  a family pack of Dreamfields pasta (7 boxes) and a $1,000 donation made in the  name of the winner to the food bank/pantry of choice. The Total Approximate  Retail Value (ARV) is $14,084. NO ENTRANT IS GUARANTEED TO WIN ANY  PRIZE OF ANY KIND.  THE ODDS OF WINNING  DEPEND ON THE NUMBER  OF ENTRIES RECEIVED.<br>
<br>
No substitution of prize or  transfer/assignment of prize to others or request for the cash equivalent by  winners is permitted. Winner must claim prize by return e-mail and providing  such winner&rsquo;s address in an eligible U.S. State within 48 (48) hours of Winner  notification. Prizes will be sent to winners/named food banks within sixty (60)  days after winners are confirmed.</li>


<li>NOTIFICATION: Winners of the Contest will be  notified by e-mail to the e-mail address provided and must respond with their  full name, address, city, state, zip code, and daytime phone number within 48  hours of attempted notification. Winner will be required to sign a release form  in order to collect their prize. Failure to collect the prizes as instructed,  the return of any prizes/prize notifications as undeliverable, Sponsor&rsquo;s  inability to contact a potential winner in a reasonable time period, or  non-compliance with these Official Rules may result in forfeiture of prize. Dreamfields  pasta shall have no liability for a winner&rsquo;s failure to receive notices due to  winners&rsquo; spam, junk e-mail or other security settings or for winners&rsquo; provision  of incorrect or otherwise non-functioning contact information. If the winner  cannot be reached after reasonable efforts have been exerted, or if he/she is  found to be ineligible, or if he/she cannot or does not comply with these  Contest Rules, such winner will be disqualified and an alternate winner may be  selected.</li>
              

<li>PUBLICITY: Except  where prohibited, participation in this Contest constitutes winner&rsquo;s consent to  use of winner&rsquo;s name, likeness, voice, opinions and biographical information  for publicity, advertising, trade, or promotional purposes in any media or  manner, now known or hereafter devised, worldwide, without further payment,  consideration, notice or approval.</li>


<li>TERMS: Dreamfields  pasta, its suppliers, agents, affiliates, consultants and service providers are  not responsible for any typographical or other error in the printing, the  offering or the announcement of any prize or in the administration of the  promotion, whether caused by computer, technical or human error. Winner assumes  all liability and agrees to hold Dreamfields pasta, its suppliers, advertisers,  agents, affiliates, consultants and service providers harmless for any injury or  damage caused, or claimed to be caused, by participation in this promotion or  use or redemption of any prize.<br>
<br>
Dreamfields pasta reserves the right to cancel  or modify the program at any time and for any reason, including but not limited  to, destruction of the integrity of the promotion by fraud, misconduct or  technical failures, or if a computer virus, bug, or other technical problem  corrupts the administration, security, or proper administration of the  promotion. Dreamfields pasta reserves the right to disqualify, freeze or  prohibit the participation of an individual if fraud or tampering is suspected,  or if the individual fails to comply with any requirement of participation or  with any provision in these Contest Rules. CAUTION: ANY ATTEMPT TO DELIBERATELY  DAMAGE OR UNDERMINE THE OPERATION OF THIS  PROMOTION MAY BE A VIOLATION OF CRIMINAL AND CIVIL LAWS.  DREAMFIELDS PASTA RESERVES THE RIGHT  TO DISQUALIFY AND/OR SEEK DAMAGES FROM  ANY INDIVIDUAL MAKING ANY SUCH  ATTEMPTS TO THE FULL EXTENT PERMITTED BY LAW.</li>


<li>RELEASE OF LIABILITY; DISCLAIMER OF WARRANTIES: By entering this Contest, entrants release  Dreamfields pasta, its suppliers, advertisers, agents, affiliates, consultants  and service providers, from any liability, loss, harm, damage, cost or expenses  whatsoever incurred which may occur in connection with any part of this Contest  and with the acceptance, ownership, and/or use of the prizes. ALL  PRIZES, WILL BE AWARDED &ldquo;AS IS,&rdquo; AND DREAMFIELDS PASTA EXPRESSLY  DISCLAIMS ALL WARRANTIES,  WHETHER EXPRESS OR IMPLIED, INCLUDING WITHOUT  LIMITATION THE IMPLIED WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.</li>


<li>PRIVACY:  Personally identifiable information that is submitted by entrants as part of  this Contest will be used to administer the Contest, select prize winners and  fulfill prizes, and will be treated in accordance with Dreamfields pasta&rsquo;s  privacy policy. 
<a href="http://www.dreamfieldsfoods.com/privacy-policy.html">http://www.dreamfieldsfoods.com/privacy-policy.html</a></li>


<li>GOVERNING LAW/JURISDICTION: all issues and  questions concerning the construction, validity, interpretation and  enforceability of these official rules or the rights and obligations of  entrants or sponsor in connection with the contest shall be governed by and  construed in accordance with the internal laws of the state of Minnesota  without giving effect to any choice of law of conflict of law rules or  provisions that would cause the application of any other state&rsquo;s laws.</li>


<li>ARBITRATION PROVISION:<br>
Any controversy or claim arising out  of or relating to this Promotion shall be settled by binding arbitration at a  location within the greater Minneapolis/St. Paul, Minnesota metropolitan area  selected by the arbitrator (provided that such location is reasonably  convenient for claimant), or at such other location as may be mutually agreed  upon by the parties, in accordance with the procedural rules for commercial  disputes set forth in the Comprehensive Arbitration Rules and Procedures of  JAMS (&ldquo;JAMS Rules and Procedures&rdquo;) then prevailing, and judgment upon the award  rendered by the arbitrator(s) may be entered in any court having jurisdiction  thereof. The arbitrator shall be selected pursuant to the JAMS Rules and  Procedures. The arbitrator shall apply Minnesota law consistent with the  Federal Arbitration Act and applicable statutes of limitations, and shall honor  claims of privilege recognized at law. In the event that the claimant is able  to demonstrate that the costs of arbitration will be prohibitive as compared to  the costs of litigation, Sponsor will pay as much of the claimant&rsquo;s filing and  hearing fees in connection with the arbitration as the arbitrator deems  necessary to prevent the arbitration from being cost-prohibitive. If any part  of this arbitration provision is deemed to be invalid, unenforceable or illegal  (other than that claims will not be arbitrated on a class or representative  basis), or otherwise conflicts with the rules and procedures established by  JAMS, then the balance of this arbitration provision shall remain in effect and  shall be construed in accordance with its terms as if the invalid,  unenforceable, illegal or conflicting provision were not contained herein. If,  however, the portion that is deemed invalid, unenforceable or illegal is that  claims will not be arbitrated on a class or representative basis, then the entirety of this arbitration provision shall be  null and void, and neither claimant nor Sponsor shall be entitled to arbitrate  their dispute. Upon filing a demand for arbitration, all parties to such  arbitration shall have the right of discovery, which discovery shall be  completed within sixty days after the demand for arbitration is made, unless  further extended by mutual agreement of the parties. THE ARBITRATION OF  DISPUTES PURSUANT TO THIS PARAGRAPH SHALL BE IN THE ENTRANT&rsquo;S INDIVIDUAL CAPACITY  AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE  PROCEEDING. THE ARBITRATOR MAY NOT CONSOLIDATE OR JOIN THE CLAIMS OF OTHER  PERSONS OR PARTIES WHO MAY BE SIMILARLY SITUATED.<br>
<br>
DO NOT ENTER THIS PROMOTION IF YOU DO  NOT AGREE TO HAVE ANY CLAIM OR CONTROVERSY ARBITRATED IN ACCORDANCE WITH THESE  OFFICIAL RULES.</li>


<li>CLASS ACTION: No class action suits. By participating in  sponsor&rsquo;s sweepstakes, each entrant and prize winner (and his/her parent/legal  guardian, if an eligible minor) agrees that to the extent permitted by  applicable law: (1) any and all disputes, claims and causes of action arising  out of or connected with the sweepstakes, or any prize awarded, will be  resolved individually without resort to any form of class action; (2) any and  all claims, judgments and awards will be limited to actual third-party,  out-of-pocket costs incurred (if any), but in no event will attorneys' fees be  awarded or recoverable; (3) UNDER NO CIRCUMSTANCES WILL ANY ENTRANT OR PRIZE  WINNER BE PERMITTED TO OBTAIN ANY AWARD FOR, AND ENTRANT HEREBY KNOWINGLY AND  EXPRESSLY WAIVES ALL RIGHTS TO SEEK PUNITIVE, INCIDENTAL, CONSEQUENTIAL OR  SPECIAL DAMAGES, LOST PROFITS AND/OR ANY OTHER DAMAGES, OTHER THAN ACTUAL OUT  OF POCKET EXPENSES, AND/OR ANY RIGHTS TO HAVE DAMAGES MULTIPLIED OR OTHERWISE  INCREASED; AND (4) ENTRANT AND PRIZE WINNER'S REMEDIES ARE LIMITED TO A CLAIM  FOR MONEY DAMAGES (IF ANY) AND ENTRANT IRREVOCABLY WAIVES ANY RIGHT TO SEEK  INJUNCTIVE OR EQUITABLE RELIEF; (5) this Promotion is governed by the laws of  the state of Minnesota without regard to its conflicts of law principles and  any and all disputes, claims and causes of action arising out of or connected  with this Promotion, and except for the arbitration noted above all disputes  shall be litigated exclusively before a court of competent jurisdiction located  within the state of New Jersey; if any provision or provisions of these  official rules shall be held  to be invalid, illegal, unenforceable or in  conflict with the law, the validity, legality and enforceability of the  remaining provisions shall not in any way be affected or impaired thereby; and  (6) entrants shall be bound by these official rules.</li>


<li>WINNERS LIST/OFFICIAL RULES: To obtain a copy of these Official Rules (print this page)  and/or any legally-required winners list, send a self-addressed stamped  envelope to: Dreamfields Pastapalooza V Contest, 155 North Michigan Ave., Suite  609, Chicago, IL 60601. All such requests must be received by 9/1/2015.</li>


<li>INDEMNIFICATION CLAUSE: Entrants (and, if eligible minors, their parents  or legal guardians) agree (a) that Sponsor and Promotion Parties are released,  will have no liability whatsoever for, and shall be held harmless by entrants  against any liability for any injuries, losses or damages of any kind to  person(s), including death, or property resulting in whole or in part, directly  or indirectly, from acceptance, possession, misuse or use of any prize or  participation in this Sweepstakes or any Sweepstakes-related activities,  including any travel related thereto and (b) except where legally prohibited,  winners (and, if eligible minors, their parents or legal guardians) grant (and  agree to confirm that grant in writing) permission to Sponsor and those acting  under their respective authority the right to the use of his/her name, picture,  likeness, persona, voice, image, biographical information and statements, at  any time or times, for advertising, trade, publicity and promotional purposes  without additional compensation, in all media now known or hereafter  discovered, worldwide in perpetuity, and on the Internet and World Wide Web, without notice, review or approval, unless prohibited by law.</li>

</ol>              

            
          </div><!-- .ca_1 -->
          
        </div>
        <!-- END page content -->
        
        
        <?php include('../_includes/footer_nav.php'); ?>
        
      </div><!-- #border_gold -->
    </div><!-- #site_body -->

<?php include('../_includes/subdir_footer.php'); ?>
<script language='javascript'>
  // mark the active page in main nav
  $("#mainnav_privacy").addClass("active");
</script>	

</body>
</html>